version: "3.1"

services:
  db:
    build:
      context: ./support
      dockerfile: Dockerfile.database.local
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./database/mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    links:
      - db
  server:
    env_file:
      - ./v3server/.env
    build:
      context: ./v3server
      dockerfile: Dockerfile.server.local
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./v3server:/server
    entrypoint: php artisan serve --host=127.0.0.1 --port=8000
    links:
      - db
  client:
    build:
      context: ./v2client
      dockerfile: Dockerfile.client.local
    image: msmf/client
    restart: always
    volumes:
      - ./v2client:/msmf/v2client
    ports:
      - 3000:3000
    entrypoint: yarn dev
    links:
      - server
