FROM node:12.22.0-alpine

ARG MSMF_CLIENT_ROOT=/msmf

COPY . ${MSMF_CLIENT_ROOT}/v2client

WORKDIR ${MSMF_CLIENT_ROOT}/v2client

RUN yarn install

ENV SERVER "http://server:8000/v1"

VOLUME ${MSMF_CLIENT_ROOT}/v2client/node_modules
